-- Migration: Create carts and cart_items tables for Shopping Cart API (US-2.1)
-- Author: Backend Lead
-- Date: 2026-03-11
-- Description: Persistent shopping cart storage with support for multi-item carts

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: carts
-- Purpose: One cart per authenticated user. Tracks cart-level metadata.
CREATE TABLE IF NOT EXISTS public.carts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT unique_user_cart UNIQUE(user_id)
);

-- Index for fast user lookup
CREATE INDEX IF NOT EXISTS idx_carts_user_id ON public.carts(user_id);

-- RLS: Enable row-level security
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only select their own cart
CREATE POLICY "Users can view their own cart"
  ON public.carts
  FOR SELECT
  USING (auth.uid() = user_id);

-- RLS Policy: Users can insert their own cart (automatic on signup)
CREATE POLICY "Users can insert their own cart"
  ON public.carts
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- RLS Policy: Users can update their own cart
CREATE POLICY "Users can update their own cart"
  ON public.carts
  FOR UPDATE
  USING (auth.uid() = user_id);

-- RLS Policy: Users can delete their own cart
CREATE POLICY "Users can delete their own cart"
  ON public.carts
  FOR DELETE
  USING (auth.uid() = user_id);

-- Table: cart_items
-- Purpose: Individual line items in a cart. One row per product per cart.
CREATE TABLE IF NOT EXISTS public.cart_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cart_id BIGINT NOT NULL REFERENCES public.carts(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT unique_product_per_cart UNIQUE(cart_id, product_id)
);

-- Index for fast cart lookup
CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON public.cart_items(cart_id);

-- Index for fast product lookup
CREATE INDEX IF NOT EXISTS idx_cart_items_product_id ON public.cart_items(product_id);

-- Index for combined lookups (used in cart updates)
CREATE INDEX IF NOT EXISTS idx_cart_items_cart_product ON public.cart_items(cart_id, product_id);

-- RLS: Enable row-level security
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only select items from their own cart
CREATE POLICY "Users can view items in their own cart"
  ON public.cart_items
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.carts
      WHERE carts.id = cart_items.cart_id
        AND carts.user_id = auth.uid()
    )
  );

-- RLS Policy: Users can insert items into their own cart
CREATE POLICY "Users can add items to their own cart"
  ON public.cart_items
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.carts
      WHERE carts.id = cart_items.cart_id
        AND carts.user_id = auth.uid()
    )
  );

-- RLS Policy: Users can update items in their own cart
CREATE POLICY "Users can update items in their own cart"
  ON public.cart_items
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.carts
      WHERE carts.id = cart_items.cart_id
        AND carts.user_id = auth.uid()
    )
  );

-- RLS Policy: Users can delete items from their own cart
CREATE POLICY "Users can remove items from their own cart"
  ON public.cart_items
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.carts
      WHERE carts.id = cart_items.cart_id
        AND carts.user_id = auth.uid()
    )
  );

-- Trigger: Update updated_at timestamp on carts
CREATE OR REPLACE FUNCTION public.update_carts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER carts_update_timestamp
  BEFORE UPDATE ON public.carts
  FOR EACH ROW
  EXECUTE FUNCTION public.update_carts_updated_at();

-- Trigger: Update updated_at timestamp on cart_items
CREATE OR REPLACE FUNCTION public.update_cart_items_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER cart_items_update_timestamp
  BEFORE UPDATE ON public.cart_items
  FOR EACH ROW
  EXECUTE FUNCTION public.update_cart_items_updated_at();

-- Trigger: Update parent cart's updated_at when items change
CREATE OR REPLACE FUNCTION public.update_cart_on_item_change()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.carts
  SET updated_at = NOW()
  WHERE id = COALESCE(NEW.cart_id, OLD.cart_id);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER cart_items_update_parent_timestamp
  AFTER INSERT OR UPDATE OR DELETE ON public.cart_items
  FOR EACH ROW
  EXECUTE FUNCTION public.update_cart_on_item_change();

-- Migration complete
-- Next: Test locally and apply to staging/production
